# Site settings
title: Question2Answer 中文说明文档
url: http://q2adoc.ostack.cn/
baseurl: /
permalink: pretty
exclude: [vendor]

# Build settings
markdown: CommonMarkGhPages
highlighter: rouge

# Menu layout
nav:
  main:
    - name: 安装
      path: /install/
      sub: 安装
    - name: 定制
      path: /themes/
      sub: 定制
    - name: 插件
      path: /plugins/
      sub: 插件
    - name: 代码
      path: /code/external/
      sub: 代码
    - name: 贡献
      path: /contribute/
      sub: 贡献
    - name: 扩展
      path: /addons/
      sub: 扩展

  second:
    - name: 服务支持
      url: /services/
      class: main-nav-link-separate
    - name: 示例网站
      url: https://www.question2answer.org/sites.php
    - name: Q&A社区
      url: https://www.question2answer.org/qa/

  footer:
    - name: 联系我们
      url: https://www.question2answer.org/feedback.php
    - name: 版本历史
      url: /install/versions/
    - name: License
      url: https://www.question2answer.org/license.php
    - name: 演示沙箱
      url: http://demo.question2answer.org/

  install:
    - name: 基础安装
      path: /install/
    - name: WordPress
      path: /install/wordpress/
    - name: 单点登录
      path: /install/single-sign-on/
    - name: 升级
      path: /install/upgrade/
    - name: 最小化
      path: /install/optimize/
    - name: 安全
      path: /install/security/
    - name: .htaccess
      path: /install/htaccess/

  customize:
    - name: 创建主题
      path: /themes/
    - name: 国际化 Q2A
      path: /translate/

  plugins:
    - name: 总览
      path: /plugins/
    - name: 模块
      path: /plugins/modules/
    - name: 图层
      path: /plugins/layers/
    - name: 重载
      path: /plugins/overrides/
    - name: 插件开发之旅
      path: /plugins/tutorial/

  code:
    - name: 扩展
      path: /code/external/
    - name: 函数
      path: /code/functions/
    - name: App 结构
      path: /code/structure/

  contribute:
    - name: 问题
      path: /contribute/
    - name: 代码风格
      path: /contribute/coding-style/
    - name: 单元测试
      path: /contribute/unit-tests/
    - name: 说明文档
      path: /contribute/docs/

  addons:
    - name: 翻译
      path: /addons/translations/
    - name: 主题
      path: /addons/themes/
    - name: 插件
      path: /addons/plugins/
    - name: 客户端
      path: /addons/clients/

