# Site settings
title: Question2Answer documentation
url: http://docs.question2answer.org
baseurl: /
permalink: pretty
exclude: [vendor]

# Build settings
markdown: CommonMarkGhPages
highlighter: rouge

# Menu layout
nav:
  main:
    - name: 安装指南
      path: /install/
      sub: install
    - name: 主题开发
      path: /themes/
      sub: customize
    - name: 插件开发
      path: /plugins/
      sub: plugins
    - name: 代码引用
      path: /code/external/
      sub: code
    - name: 贡献社区
      path: /contribute/
      sub: contribute
    - name: 扩展程序
      path: /addons/
      sub: addons

  second:
    - name: 服务支持
      url: /services/
      class: main-nav-link-separate
    - name: 示例网站
      url: https://www.question2answer.org/sites.php
    - name: Q&A社区
      url: https://www.question2answer.org/qa/

  footer:
    - name: 联系我们
      url: https://www.question2answer.org/feedback.php
    - name: 版本记录
      url: /install/versions/
    - name: License details
      url: https://www.question2answer.org/license.php
    - name: 演示沙箱
      url: http://demo.question2answer.org/

  install:
    - name: 安装
      path: /install/
    - name: 升级
      path: /install/upgrade/
    - name: 安全
      path: /install/security/
    - name: 单点登录
      path: /install/single-sign-on/
    - name: WordPress集成
      path: /install/wordpress/
    - name: .htaccess
      path: /install/htaccess/

  customize:
    - name: 主题创建
      path: /themes/
    - name: Q2A国际化
      path: /translate/

  plugins:
    - name: 总览
      path: /plugins/
    - name: 模块
      path: /plugins/modules/
    - name: 页面
      path: /plugins/layers/
    - name: 重载
      path: /plugins/overrides/
    - name: 插件开发
      path: /plugins/tutorial/

  code:
    - name: 外部引用
      path: /code/external/
    - name: 功能
      path: /code/functions/
    - name: App结构
      path: /code/structure/

  contribute:
    - name: 问题
      path: /contribute/
    - name: 代码风格
      path: /contribute/coding-style/
    - name: 单元测试
      path: /contribute/unit-tests/
    - name: 说明文档
      path: /contribute/docs/

  addons:
    - name: 翻译
      path: /addons/translations/
    - name: 主题
      path: /addons/themes/
    - name: 插件
      path: /addons/plugins/
    - name: 客户端
      path: /addons/clients/

